"""
Section-by-section edges for Landesbauordnung für Baden-Württemberg (LBO BW).

Generated by generate_state_section_edges.py: structural (supplements, sub_item_of)
from the fine inventory plus MBO-projected domain edges. Review and adapt.
"""

from __future__ import annotations

from typing import List

from propra.graph.schema import Edge


def section_1_anwendungsbereich() -> List[Edge]:
    """§1 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§1_1.1",
        target="BW_LBO_§1",
        relation="supplements",
        sourced_from="§1 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§1_2.1",
        target="BW_LBO_§1",
        relation="supplements",
        sourced_from="§1 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§1_3.1",
        target="BW_LBO_§1",
        relation="supplements",
        sourced_from="§1 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§1_4.1",
        target="BW_LBO_§1",
        relation="supplements",
        sourced_from="§1 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§1_5.1",
        target="BW_LBO_§1",
        relation="supplements",
        sourced_from="§1 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§1_6.1",
        target="BW_LBO_§1",
        relation="supplements",
        sourced_from="§1 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§1_7.1",
        target="BW_LBO_§1",
        relation="supplements",
        sourced_from="§1 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§1_8.1",
        target="BW_LBO_§1",
        relation="supplements",
        sourced_from="§1 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_2_begriffe() -> List[Edge]:
    """§2 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§2_10.1",
        target="BW_LBO_§2",
        relation="supplements",
        sourced_from="§2 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§2_11.1",
        target="BW_LBO_§2",
        relation="supplements",
        sourced_from="§2 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§2_12.1",
        target="BW_LBO_§2",
        relation="supplements",
        sourced_from="§2 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§2_13.1",
        target="BW_LBO_§2",
        relation="supplements",
        sourced_from="§2 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§2_14.1",
        target="BW_LBO_§2",
        relation="supplements",
        sourced_from="§2 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_3_allgemeine_anforderungen() -> List[Edge]:
    """§3 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§3_1.1",
        target="BW_LBO_§3",
        relation="supplements",
        sourced_from="§3 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§3_2.1",
        target="BW_LBO_§3",
        relation="supplements",
        sourced_from="§3 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§3_3.1",
        target="BW_LBO_§3",
        relation="supplements",
        sourced_from="§3 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_4_bebauung_der_grundstuecke() -> List[Edge]:
    """§4 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§4_1.1",
        target="BW_LBO_§4",
        relation="supplements",
        sourced_from="§4 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§4_2.1",
        target="BW_LBO_§4",
        relation="supplements",
        sourced_from="§4 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§4_3.1",
        target="BW_LBO_§4",
        relation="supplements",
        sourced_from="§4 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_5_abstandsflaechen() -> List[Edge]:
    """§5 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§5_1.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_2.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_3.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_4.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_5.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_6.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_7.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_7.2",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_8.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_9.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_9.2",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_10.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_11.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_12.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_13.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_14.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_15.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_16.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_17.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_18.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_19.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_20.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_21.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_22.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_23.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_24.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_25.1",
        target="BW_LBO_§5",
        relation="supplements",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_7.2",
        target="BW_LBO_§5_7.1",
        relation="sub_item_of",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§5_9.2",
        target="BW_LBO_§5_9.1",
        relation="sub_item_of",
        sourced_from="§5 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_6_abstandsflaechen_in_sonderfaellen() -> List[Edge]:
    """§6 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§6_5.1",
        target="BW_LBO_§6",
        relation="supplements",
        sourced_from="§6 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§6_6.1",
        target="BW_LBO_§6",
        relation="supplements",
        sourced_from="§6 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§6_7.1",
        target="BW_LBO_§6",
        relation="supplements",
        sourced_from="§6 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§6_8.1",
        target="BW_LBO_§6",
        relation="supplements",
        sourced_from="§6 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§6_9.1",
        target="BW_LBO_§6",
        relation="supplements",
        sourced_from="§6 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§6_10.1",
        target="BW_LBO_§6",
        relation="supplements",
        sourced_from="§6 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_7_uebernahme_von_abstaenden_auf_nachbargrundstueck() -> List[Edge]:
    """§7 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§7_1.1",
        target="BW_LBO_§7",
        relation="supplements",
        sourced_from="§7 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_8_teilung_von_grundstuecken() -> List[Edge]:
    """§8 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§8_1.1",
        target="BW_LBO_§8",
        relation="supplements",
        sourced_from="§8 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§8_2.1",
        target="BW_LBO_§8",
        relation="supplements",
        sourced_from="§8 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§8_2.1",
        target="BW_LBO_§8_1.1",
        relation="references",
        sourced_from="§8 BW_LBO",
        metadata={"reasoning": "Structure inherited from MBO via section mapping.", "mbo_edge": "MBO_§7_2.1 -> MBO_§7_1.1"},
    ))
    return edges

def section_9_nichtueberbaute_flaechen_kinderspielplaetze() -> List[Edge]:
    """§9 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§9_1.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_2.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_3.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_4.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_5.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.2",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.3",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.4",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.5",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.6",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_7.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_8.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_9.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_10.1",
        target="BW_LBO_§9",
        relation="supplements",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.2",
        target="BW_LBO_§9_6.1",
        relation="sub_item_of",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.3",
        target="BW_LBO_§9_6.1",
        relation="sub_item_of",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.4",
        target="BW_LBO_§9_6.1",
        relation="sub_item_of",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.5",
        target="BW_LBO_§9_6.1",
        relation="sub_item_of",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§9_6.6",
        target="BW_LBO_§9_6.1",
        relation="sub_item_of",
        sourced_from="§9 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_10_hoehenlage_des_grundstuecks() -> List[Edge]:
    """§10 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§10_1.1",
        target="BW_LBO_§10",
        relation="supplements",
        sourced_from="§10 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_11_gestaltung() -> List[Edge]:
    """§11 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§11_1.1",
        target="BW_LBO_§11",
        relation="supplements",
        sourced_from="§11 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§11_1.2",
        target="BW_LBO_§11",
        relation="supplements",
        sourced_from="§11 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§11_2.1",
        target="BW_LBO_§11",
        relation="supplements",
        sourced_from="§11 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§11_3.1",
        target="BW_LBO_§11",
        relation="supplements",
        sourced_from="§11 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§11_1.2",
        target="BW_LBO_§11_1.1",
        relation="sub_item_of",
        sourced_from="§11 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_12_baustelle() -> List[Edge]:
    """§12 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§12_1.1",
        target="BW_LBO_§12",
        relation="supplements",
        sourced_from="§12 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§12_2.1",
        target="BW_LBO_§12",
        relation="supplements",
        sourced_from="§12 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§12_3.1",
        target="BW_LBO_§12",
        relation="supplements",
        sourced_from="§12 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_13_standsicherheit() -> List[Edge]:
    """§13 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§13_1.1",
        target="BW_LBO_§13",
        relation="supplements",
        sourced_from="§13 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§13_1.2",
        target="BW_LBO_§13",
        relation="supplements",
        sourced_from="§13 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§13_1.2",
        target="BW_LBO_§13_1.1",
        relation="sub_item_of",
        sourced_from="§13 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_14_schutz_baulicher_anlagen() -> List[Edge]:
    """§14 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§14_1.1",
        target="BW_LBO_§14",
        relation="supplements",
        sourced_from="§14 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_15_brandschutz() -> List[Edge]:
    """§15 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§15_1.1",
        target="BW_LBO_§15",
        relation="supplements",
        sourced_from="§15 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§15_2.1",
        target="BW_LBO_§15",
        relation="supplements",
        sourced_from="§15 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§15_3.1",
        target="BW_LBO_§15",
        relation="supplements",
        sourced_from="§15 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§15_4.1",
        target="BW_LBO_§15",
        relation="supplements",
        sourced_from="§15 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§15_5.1",
        target="BW_LBO_§15",
        relation="supplements",
        sourced_from="§15 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§15_6.1",
        target="BW_LBO_§15",
        relation="supplements",
        sourced_from="§15 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§15_7.1",
        target="BW_LBO_§15",
        relation="supplements",
        sourced_from="§15 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_16_verkehrssicherheit() -> List[Edge]:
    """§16 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§16_1.1",
        target="BW_LBO_§16",
        relation="supplements",
        sourced_from="§16 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§16_2.1",
        target="BW_LBO_§16",
        relation="supplements",
        sourced_from="§16 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_27a_aussenwaende() -> List[Edge]:
    """§27a BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§27a_1.1",
        target="BW_LBO_§27a",
        relation="supplements",
        sourced_from="§27a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27a_2.1",
        target="BW_LBO_§27a",
        relation="supplements",
        sourced_from="§27a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27a_3.1",
        target="BW_LBO_§27a",
        relation="supplements",
        sourced_from="§27a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27a_4.1",
        target="BW_LBO_§27a",
        relation="supplements",
        sourced_from="§27a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27a_5.1",
        target="BW_LBO_§27a",
        relation="supplements",
        sourced_from="§27a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_27b_trennwaende() -> List[Edge]:
    """§27b BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§27b_1.1",
        target="BW_LBO_§27b",
        relation="supplements",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27b_2.1",
        target="BW_LBO_§27b",
        relation="supplements",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27b_3.1",
        target="BW_LBO_§27b",
        relation="supplements",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27b_4.1",
        target="BW_LBO_§27b",
        relation="supplements",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27b_5.1",
        target="BW_LBO_§27b",
        relation="supplements",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27b_6.1",
        target="BW_LBO_§27b",
        relation="supplements",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27b_6.2",
        target="BW_LBO_§27b",
        relation="supplements",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27b_6.2",
        target="BW_LBO_§27b_6.1",
        relation="sub_item_of",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27b_6.1",
        target="BW_LBO_§27b",
        relation="exception_of",
        sourced_from="§27b BW_LBO",
        metadata={"reasoning": "Structure inherited from MBO via section mapping.", "mbo_edge": "MBO_§29_6.1 -> MBO_§29"},
    ))
    return edges

def section_27c_brandwaende() -> List[Edge]:
    """§27c BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§27c_1.1",
        target="BW_LBO_§27c",
        relation="supplements",
        sourced_from="§27c BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27c_2.1",
        target="BW_LBO_§27c",
        relation="supplements",
        sourced_from="§27c BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27c_3.1",
        target="BW_LBO_§27c",
        relation="supplements",
        sourced_from="§27c BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27c_4.1",
        target="BW_LBO_§27c",
        relation="supplements",
        sourced_from="§27c BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_27e_daecher() -> List[Edge]:
    """§27e BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§27e_1.1",
        target="BW_LBO_§27e",
        relation="supplements",
        sourced_from="§27e BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27e_2.1",
        target="BW_LBO_§27e",
        relation="supplements",
        sourced_from="§27e BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_27f_nutzungsaenderungen_im_bestand_tragende_bauteile() -> List[Edge]:
    """§27f BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§27f_1.1",
        target="BW_LBO_§27f",
        relation="supplements",
        sourced_from="§27f BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§27f_2.1",
        target="BW_LBO_§27f",
        relation="supplements",
        sourced_from="§27f BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_28_treppen() -> List[Edge]:
    """§28 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§28_1.1",
        target="BW_LBO_§28",
        relation="supplements",
        sourced_from="§28 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28_2.1",
        target="BW_LBO_§28",
        relation="supplements",
        sourced_from="§28 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28_3.1",
        target="BW_LBO_§28",
        relation="supplements",
        sourced_from="§28 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28_4.1",
        target="BW_LBO_§28",
        relation="supplements",
        sourced_from="§28 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28_5.1",
        target="BW_LBO_§28",
        relation="supplements",
        sourced_from="§28 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28_5.2",
        target="BW_LBO_§28",
        relation="supplements",
        sourced_from="§28 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28_5.2",
        target="BW_LBO_§28_5.1",
        relation="sub_item_of",
        sourced_from="§28 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_28a_notwendige_treppenraeume_ausgaenge() -> List[Edge]:
    """§28a BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§28a_1.1",
        target="BW_LBO_§28a",
        relation="supplements",
        sourced_from="§28a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28a_2.1",
        target="BW_LBO_§28a",
        relation="supplements",
        sourced_from="§28a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28a_3.1",
        target="BW_LBO_§28a",
        relation="supplements",
        sourced_from="§28a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_28b_notwendige_flure_offene_gaenge() -> List[Edge]:
    """§28b BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§28b_1.1",
        target="BW_LBO_§28b",
        relation="supplements",
        sourced_from="§28b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28b_2.1",
        target="BW_LBO_§28b",
        relation="supplements",
        sourced_from="§28b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28b_2.2",
        target="BW_LBO_§28b",
        relation="supplements",
        sourced_from="§28b BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28b_2.2",
        target="BW_LBO_§28b_2.1",
        relation="sub_item_of",
        sourced_from="§28b BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_28c_fenster_sonstige_oeffnungen() -> List[Edge]:
    """§28c BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§28c_1.1",
        target="BW_LBO_§28c",
        relation="supplements",
        sourced_from="§28c BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§28c_2.1",
        target="BW_LBO_§28c",
        relation="supplements",
        sourced_from="§28c BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_28d_nutzungsaenderungen_bei_bauteilen_im_bestand() -> List[Edge]:
    """§28d BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§28d_1.1",
        target="BW_LBO_§28d",
        relation="supplements",
        sourced_from="§28d BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_29_aufzugsanlagen() -> List[Edge]:
    """§29 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§29_1.1",
        target="BW_LBO_§29",
        relation="supplements",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_2.1",
        target="BW_LBO_§29",
        relation="supplements",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_3.1",
        target="BW_LBO_§29",
        relation="supplements",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_3.2",
        target="BW_LBO_§29",
        relation="supplements",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_4.1",
        target="BW_LBO_§29",
        relation="supplements",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_4.2",
        target="BW_LBO_§29",
        relation="supplements",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_5.1",
        target="BW_LBO_§29",
        relation="supplements",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_6.1",
        target="BW_LBO_§29",
        relation="supplements",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_3.2",
        target="BW_LBO_§29_3.1",
        relation="sub_item_of",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§29_4.2",
        target="BW_LBO_§29_4.1",
        relation="sub_item_of",
        sourced_from="§29 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_34_aufenthaltsraeume() -> List[Edge]:
    """§34 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§34_1.1",
        target="BW_LBO_§34",
        relation="supplements",
        sourced_from="§34 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§34_2.1",
        target="BW_LBO_§34",
        relation="supplements",
        sourced_from="§34 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§34_3.1",
        target="BW_LBO_§34",
        relation="supplements",
        sourced_from="§34 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§34_4.1",
        target="BW_LBO_§34",
        relation="supplements",
        sourced_from="§34 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§34_4.2",
        target="BW_LBO_§34",
        relation="supplements",
        sourced_from="§34 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§34_5.1",
        target="BW_LBO_§34",
        relation="supplements",
        sourced_from="§34 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§34_4.2",
        target="BW_LBO_§34_4.1",
        relation="sub_item_of",
        sourced_from="§34 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_35_wohnungen() -> List[Edge]:
    """§35 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§35_1.1",
        target="BW_LBO_§35",
        relation="supplements",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_2.1",
        target="BW_LBO_§35",
        relation="supplements",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_3.1",
        target="BW_LBO_§35",
        relation="supplements",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_4.1",
        target="BW_LBO_§35",
        relation="supplements",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_5.1",
        target="BW_LBO_§35",
        relation="supplements",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_5.2",
        target="BW_LBO_§35",
        relation="supplements",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_6.1",
        target="BW_LBO_§35",
        relation="supplements",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_7.1",
        target="BW_LBO_§35",
        relation="supplements",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_5.2",
        target="BW_LBO_§35_5.1",
        relation="sub_item_of",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_5.1",
        target="BW_LBO_§6",
        relation="references",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Structure inherited from MBO via section mapping.", "mbo_edge": "MBO_§48_5.1 -> MBO_§6"},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_5.1",
        target="BW_LBO_§27a",
        relation="references",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Structure inherited from MBO via section mapping.", "mbo_edge": "MBO_§48_5.1 -> MBO_§28"},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_5.1",
        target="BW_LBO_§27c",
        relation="references",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Structure inherited from MBO via section mapping.", "mbo_edge": "MBO_§48_5.1 -> MBO_§30"},
    ))
    edges.append(Edge(
        source="BW_LBO_§35_5.1",
        target="BW_LBO_§27e",
        relation="references",
        sourced_from="§35 BW_LBO",
        metadata={"reasoning": "Structure inherited from MBO via section mapping.", "mbo_edge": "MBO_§48_5.1 -> MBO_§32"},
    ))
    return edges

def section_36_toilettenraeume_und_baeder() -> List[Edge]:
    """§36 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§36_1.1",
        target="BW_LBO_§36",
        relation="supplements",
        sourced_from="§36 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§36_2.1",
        target="BW_LBO_§36",
        relation="supplements",
        sourced_from="§36 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_37_stellplaetze_fuer_kraftfahrzeuge_und_fahrraeder_() -> List[Edge]:
    """§37 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§37_1.1",
        target="BW_LBO_§37",
        relation="supplements",
        sourced_from="§37 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§37_2.1",
        target="BW_LBO_§37",
        relation="supplements",
        sourced_from="§37 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§37_3.1",
        target="BW_LBO_§37",
        relation="supplements",
        sourced_from="§37 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§37_3.2",
        target="BW_LBO_§37",
        relation="supplements",
        sourced_from="§37 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§37_4.1",
        target="BW_LBO_§37",
        relation="supplements",
        sourced_from="§37 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§37_5.1",
        target="BW_LBO_§37",
        relation="supplements",
        sourced_from="§37 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§37_3.2",
        target="BW_LBO_§37_3.1",
        relation="sub_item_of",
        sourced_from="§37 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_39_barrierefreie_anlagen() -> List[Edge]:
    """§39 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§39_1.1",
        target="BW_LBO_§39",
        relation="supplements",
        sourced_from="§39 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§39_2.1",
        target="BW_LBO_§39",
        relation="supplements",
        sourced_from="§39 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§39_3.1",
        target="BW_LBO_§39",
        relation="supplements",
        sourced_from="§39 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_40_gemeinschaftsanlagen() -> List[Edge]:
    """§40 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§40_1.1",
        target="BW_LBO_§40",
        relation="supplements",
        sourced_from="§40 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§40_2.1",
        target="BW_LBO_§40",
        relation="supplements",
        sourced_from="§40 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_49_genehmigungspflichtige_vorhaben() -> List[Edge]:
    """§49 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§49_1.1",
        target="BW_LBO_§49",
        relation="supplements",
        sourced_from="§49 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_50_verfahrensfreie_vorhaben() -> List[Edge]:
    """§50 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§50_1.1",
        target="BW_LBO_§50",
        relation="supplements",
        sourced_from="§50 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§50_2.1",
        target="BW_LBO_§50",
        relation="supplements",
        sourced_from="§50 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§50_3.1",
        target="BW_LBO_§50",
        relation="supplements",
        sourced_from="§50 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_51_kenntnisgabeverfahren() -> List[Edge]:
    """§51 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§51_1.1",
        target="BW_LBO_§51",
        relation="supplements",
        sourced_from="§51 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§51_2.1",
        target="BW_LBO_§51",
        relation="supplements",
        sourced_from="§51 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§51_3.1",
        target="BW_LBO_§51",
        relation="supplements",
        sourced_from="§51 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§51_4.1",
        target="BW_LBO_§51",
        relation="supplements",
        sourced_from="§51 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_52_vereinfachtes_baugenehmigungsverfahren() -> List[Edge]:
    """§52 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§52_1.1",
        target="BW_LBO_§52",
        relation="supplements",
        sourced_from="§52 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§52_2.1",
        target="BW_LBO_§52",
        relation="supplements",
        sourced_from="§52 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§52_3.1",
        target="BW_LBO_§52",
        relation="supplements",
        sourced_from="§52 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§52_4.1",
        target="BW_LBO_§52",
        relation="supplements",
        sourced_from="§52 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_53_bauvorlagen_und_bauantrag() -> List[Edge]:
    """§53 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§53_1.1",
        target="BW_LBO_§53",
        relation="supplements",
        sourced_from="§53 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§53_2.1",
        target="BW_LBO_§53",
        relation="supplements",
        sourced_from="§53 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_54_fristen_im_genehmigungsverfahren() -> List[Edge]:
    """§54 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§54_1.1",
        target="BW_LBO_§54",
        relation="supplements",
        sourced_from="§54 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§54_2.1",
        target="BW_LBO_§54",
        relation="supplements",
        sourced_from="§54 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§54_3.1",
        target="BW_LBO_§54",
        relation="supplements",
        sourced_from="§54 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§54_4.1",
        target="BW_LBO_§54",
        relation="supplements",
        sourced_from="§54 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§54_5.1",
        target="BW_LBO_§54",
        relation="supplements",
        sourced_from="§54 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_55_benachrichtigung_der_nachbarn() -> List[Edge]:
    """§55 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§55_1.1",
        target="BW_LBO_§55",
        relation="supplements",
        sourced_from="§55 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§55_2.1",
        target="BW_LBO_§55",
        relation="supplements",
        sourced_from="§55 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§55_3.1",
        target="BW_LBO_§55",
        relation="supplements",
        sourced_from="§55 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_56_abweichungen_ausnahmen_und_befreiungen() -> List[Edge]:
    """§56 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§56_1.1",
        target="BW_LBO_§56",
        relation="supplements",
        sourced_from="§56 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§56_2.1",
        target="BW_LBO_§56",
        relation="supplements",
        sourced_from="§56 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§56_3.1",
        target="BW_LBO_§56",
        relation="supplements",
        sourced_from="§56 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§56_4.1",
        target="BW_LBO_§56",
        relation="supplements",
        sourced_from="§56 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_57_bauvorbescheid() -> List[Edge]:
    """§57 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§57_1.1",
        target="BW_LBO_§57",
        relation="supplements",
        sourced_from="§57 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§57_2.1",
        target="BW_LBO_§57",
        relation="supplements",
        sourced_from="§57 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_58_baugenehmigung() -> List[Edge]:
    """§58 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§58_1.1",
        target="BW_LBO_§58",
        relation="supplements",
        sourced_from="§58 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§58_2.1",
        target="BW_LBO_§58",
        relation="supplements",
        sourced_from="§58 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§58_3.1",
        target="BW_LBO_§58",
        relation="supplements",
        sourced_from="§58 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§58_4.1",
        target="BW_LBO_§58",
        relation="supplements",
        sourced_from="§58 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_59_baubeginn() -> List[Edge]:
    """§59 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§59_1.1",
        target="BW_LBO_§59",
        relation="supplements",
        sourced_from="§59 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§59_2.1",
        target="BW_LBO_§59",
        relation="supplements",
        sourced_from="§59 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_60_sicherheitsleistung() -> List[Edge]:
    """§60 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§60_1.1",
        target="BW_LBO_§60",
        relation="supplements",
        sourced_from="§60 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_68_typengenehmigung_typenpruefung() -> List[Edge]:
    """§68 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§68_1.1",
        target="BW_LBO_§68",
        relation="supplements",
        sourced_from="§68 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§68_2.1",
        target="BW_LBO_§68",
        relation="supplements",
        sourced_from="§68 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§68_3.1",
        target="BW_LBO_§68",
        relation="supplements",
        sourced_from="§68 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_73_rechtsverordnungen() -> List[Edge]:
    """§73 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§73_1.1",
        target="BW_LBO_§73",
        relation="supplements",
        sourced_from="§73 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§73_1.2",
        target="BW_LBO_§73",
        relation="supplements",
        sourced_from="§73 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§73_1.2",
        target="BW_LBO_§73_1.1",
        relation="sub_item_of",
        sourced_from="§73 BW_LBO",
        metadata={"reasoning": "List item under same paragraph block (structural)."},
    ))
    return edges

def section_73a_technische_baubestimmungen() -> List[Edge]:
    """§73a BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§73a_1.1",
        target="BW_LBO_§73a",
        relation="supplements",
        sourced_from="§73a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§73a_2.1",
        target="BW_LBO_§73a",
        relation="supplements",
        sourced_from="§73a BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_74_oertliche_bauvorschriften() -> List[Edge]:
    """§74 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§74_1.1",
        target="BW_LBO_§74",
        relation="supplements",
        sourced_from="§74 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§74_2.1",
        target="BW_LBO_§74",
        relation="supplements",
        sourced_from="§74 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_75_ordnungswidrigkeiten() -> List[Edge]:
    """§75 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§75_1.1",
        target="BW_LBO_§75",
        relation="supplements",
        sourced_from="§75 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§75_2.1",
        target="BW_LBO_§75",
        relation="supplements",
        sourced_from="§75 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges

def section_76_bestehende_bauliche_anlagen() -> List[Edge]:
    """§76 BW_LBO — structural + MBO-projected; review and adapt."""
    edges: List[Edge] = []
    edges.append(Edge(
        source="BW_LBO_§76_1.1",
        target="BW_LBO_§76",
        relation="supplements",
        sourced_from="§76 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§76_2.1",
        target="BW_LBO_§76",
        relation="supplements",
        sourced_from="§76 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    edges.append(Edge(
        source="BW_LBO_§76_3.1",
        target="BW_LBO_§76",
        relation="supplements",
        sourced_from="§76 BW_LBO",
        metadata={"reasoning": "Content node under section (structural)."},
    ))
    return edges


def edges() -> List[Edge]:
    """Aggregate all section-defined edges (structural + domain)."""
    all_edges: List[Edge] = []
    all_edges.extend(section_1_anwendungsbereich())
    all_edges.extend(section_2_begriffe())
    all_edges.extend(section_3_allgemeine_anforderungen())
    all_edges.extend(section_4_bebauung_der_grundstuecke())
    all_edges.extend(section_5_abstandsflaechen())
    all_edges.extend(section_6_abstandsflaechen_in_sonderfaellen())
    all_edges.extend(section_7_uebernahme_von_abstaenden_auf_nachbargrundstueck())
    all_edges.extend(section_8_teilung_von_grundstuecken())
    all_edges.extend(section_9_nichtueberbaute_flaechen_kinderspielplaetze())
    all_edges.extend(section_10_hoehenlage_des_grundstuecks())
    all_edges.extend(section_11_gestaltung())
    all_edges.extend(section_12_baustelle())
    all_edges.extend(section_13_standsicherheit())
    all_edges.extend(section_14_schutz_baulicher_anlagen())
    all_edges.extend(section_15_brandschutz())
    all_edges.extend(section_16_verkehrssicherheit())
    all_edges.extend(section_27a_aussenwaende())
    all_edges.extend(section_27b_trennwaende())
    all_edges.extend(section_27c_brandwaende())
    all_edges.extend(section_27e_daecher())
    all_edges.extend(section_27f_nutzungsaenderungen_im_bestand_tragende_bauteile())
    all_edges.extend(section_28_treppen())
    all_edges.extend(section_28a_notwendige_treppenraeume_ausgaenge())
    all_edges.extend(section_28b_notwendige_flure_offene_gaenge())
    all_edges.extend(section_28c_fenster_sonstige_oeffnungen())
    all_edges.extend(section_28d_nutzungsaenderungen_bei_bauteilen_im_bestand())
    all_edges.extend(section_29_aufzugsanlagen())
    all_edges.extend(section_34_aufenthaltsraeume())
    all_edges.extend(section_35_wohnungen())
    all_edges.extend(section_36_toilettenraeume_und_baeder())
    all_edges.extend(section_37_stellplaetze_fuer_kraftfahrzeuge_und_fahrraeder_())
    all_edges.extend(section_39_barrierefreie_anlagen())
    all_edges.extend(section_40_gemeinschaftsanlagen())
    all_edges.extend(section_49_genehmigungspflichtige_vorhaben())
    all_edges.extend(section_50_verfahrensfreie_vorhaben())
    all_edges.extend(section_51_kenntnisgabeverfahren())
    all_edges.extend(section_52_vereinfachtes_baugenehmigungsverfahren())
    all_edges.extend(section_53_bauvorlagen_und_bauantrag())
    all_edges.extend(section_54_fristen_im_genehmigungsverfahren())
    all_edges.extend(section_55_benachrichtigung_der_nachbarn())
    all_edges.extend(section_56_abweichungen_ausnahmen_und_befreiungen())
    all_edges.extend(section_57_bauvorbescheid())
    all_edges.extend(section_58_baugenehmigung())
    all_edges.extend(section_59_baubeginn())
    all_edges.extend(section_60_sicherheitsleistung())
    all_edges.extend(section_68_typengenehmigung_typenpruefung())
    all_edges.extend(section_73_rechtsverordnungen())
    all_edges.extend(section_73a_technische_baubestimmungen())
    all_edges.extend(section_74_oertliche_bauvorschriften())
    all_edges.extend(section_75_ordnungswidrigkeiten())
    all_edges.extend(section_76_bestehende_bauliche_anlagen())
    return all_edges
