"""
Generic structural edge builder for state LBO knowledge graphs.

Replaces per-state edge modules (e.g. bbgbo_section_edges.py).
Works for any inventory whose node IDs follow the pattern:
    {PREFIX}§N_B.S   (content node, e.g. BbgBO_§6_6.2)
    {PREFIX}§N       (section anchor, e.g. BbgBO_§6)

Produces:
    sub_item_of : §N_B.S → §N_B.1  (list items → lead row, when S > 1)

supplements edges (content nodes → section anchor) are generated by the
shared _add_structural_edges pass in build_graph.py, which groups nodes
by source_paragraph and picks the alphabetically-first node as anchor.
Since {PREFIX}§N sorts before {PREFIX}§N_*, it naturally becomes the anchor.
"""

import re
from collections import defaultdict

import networkx as nx

from propra.graph.schema import Edge


def state_structural_edges(G: nx.DiGraph, prefix: str) -> list[Edge]:
    """
    Build sub_item_of edges for a state LBO subgraph.

    For each section, groups content nodes by their block number (the B in §N_B.S).
    Within each block, node B.1 is the lead; B.2, B.3, ... are sub-items of B.1.

    Args:
        G:      The full knowledge graph (NetworkX DiGraph).
        prefix: Node ID prefix for this state, e.g. 'BbgBO_'.

    Returns:
        List of Edge objects ready to be added with add_edge().
    """
    edges: list[Edge] = []
    law_name = prefix.rstrip("_")

    # section_num -> [(nid, block, sub), ...]
    by_section: dict[str, list[tuple[str, str, int]]] = defaultdict(list)

    for nid in G.nodes():
        if not nid.startswith(prefix):
            continue
        rest = nid[len(prefix):]
        m = re.match(r"§(\d+[a-z]?)_(\d+)\.(\d+)$", rest)
        if not m:
            continue
        section_num, block, sub = m.group(1), m.group(2), int(m.group(3))
        by_section[section_num].append((nid, block, sub))

    for section_num, node_list in by_section.items():
        sp = f"§{section_num} {law_name}"

        block_lead: dict[str, str] = {}
        block_members: dict[str, list[str]] = defaultdict(list)

        for nid, block, sub in node_list:
            if sub == 1:
                block_lead[block] = nid
            else:
                block_members[block].append(nid)

        for block, lead_nid in block_lead.items():
            for member_nid in block_members.get(block, []):
                edges.append(Edge(
                    source=member_nid,
                    target=lead_nid,
                    relation="sub_item_of",
                    sourced_from=sp,
                    metadata={"reasoning": "List item under same paragraph block (state law)."},
                ))

    return edges
